services:
  avorion:
    image: steamcmd:custom
    build: ./avorion
    entrypoint: /entrypoint.sh
    ports:
      - 27000:27000/udp
      - 27000:27000/tcp
      - 27003:27003/udp
      - 27020:27020/udp
      - 27021:27021/udp
    volumes:
      - ./avorion/data:/avorion:rw
